kotlin.code.style=official

org.gradle.jvmargs=-Xms128m -Xmx1024m
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.stability.nowarn=true
kotlin.native.ignoreDisabledTargets=true

rocksdbPrebuiltBaseUrl=https://github.com/marykdb/build-rocksdb/releases/download
rocksdbPrebuiltVersion=rocksdb-10.10.1-20260712T194246Z
rocksdbPrebuiltSha.androidNativeArm32=dc7347c499bdb7c6fac79c7b03824f0e9053f944a2a27ee313deef661b9b8fb2
rocksdbPrebuiltSha.androidNativeArm64=dd49e2af194b6ad701ed5feb756f4af716bd9aa0d2eaebb0194737410aeddc20
rocksdbPrebuiltSha.androidNativeX64=fa83f04c27d812c3b7c92c3dc49b69422849f59b6d5d9155e3611723986558a9
rocksdbPrebuiltSha.androidNativeX86=b5aac223324dc4041a32f40d93c812f6ee23ca653a57fceab04ad344d394b3c1
rocksdbPrebuiltSha.iosArm64=2d9af5769f4838a2a02f1d0955991ee575431c9125805f647b0aed55ef074101
rocksdbPrebuiltSha.iosSimulatorArm64=f965a360c64f0b3da2e286e1d73f4c8c1fa7d078f24ad762e3ac8ba76a4775f8
rocksdbPrebuiltSha.linuxArm64=dfaa7970af958ec1b2679ffa2c581372c523452fd2b63fb06269e068cc54eda2
rocksdbPrebuiltSha.linuxX64=bbe1647aa8082daa7380890b740186495dcf56974a9c7fa56813d6e3df59a271
rocksdbPrebuiltSha.macosArm64=a3189db12f93a61c1c55989531e43fef6a9a2964e1c7b8a6f8709ab9ef1aa856
rocksdbPrebuiltSha.macosX64=df1f1461b959a52bd7ecb116188d49c3f6054b8c545bdbee438162b61d5d2ea3
rocksdbPrebuiltSha.mingwX64=b158f77416cbc6c3e9153a018a662c77e41f44cabd46cbab14bc689ab29b6886
rocksdbPrebuiltSha.tvosArm64=cc024cf85ccecf2976e355d881b46fd33d268cb8ff426a70070043300654237a
rocksdbPrebuiltSha.tvosSimulatorArm64=6048d356f7401202244e87c4c07dab5425664f69b0083fbe6c9cf36c1e4550dd
rocksdbPrebuiltSha.watchosArm64=fb59d706c0790a49c336fccdcaa3ad415589f987454ebb820697afc52f30f343
rocksdbPrebuiltSha.watchosDeviceArm64=9c845e9452f3c02c83920ca51f05d1e177f984ac6e5ef2ffdbda94eaa8e35bbf
rocksdbPrebuiltSha.watchosSimulatorArm64=428d5f29f2502d4b03b3336d62e31776b03d94f0a497c8bc6d37872028221878
