kotlin.code.style=official

org.gradle.jvmargs=-Xms128m -Xmx1024m
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.stability.nowarn=true
kotlin.native.ignoreDisabledTargets=true

rocksdbPrebuiltBaseUrl=https://github.com/marykdb/build-rocksdb/releases/download
rocksdbPrebuiltVersion=rocksdb-10.10.1-20260603T074359Z
rocksdbPrebuiltSha.androidNativeArm32=ab4a7b8a436fe4444431bccdc4450cfc3905cb487ebe0abde4af385795874894
rocksdbPrebuiltSha.androidNativeArm64=2aed57c3c7fd2823e4f803ad83dffb1e6d0bab921a7756f8c11969123bf25f99
rocksdbPrebuiltSha.androidNativeX64=f3bbb87032401ef4917231f24b38ecaa3274110136cb40e5a0344e625379b08c
rocksdbPrebuiltSha.androidNativeX86=90eaac8390f99789f802607951f3a5f79ce816422a63bda5484e977c9b88f827
rocksdbPrebuiltSha.iosArm64=51732b2a190e3944a8a3d15e013c9416c90f2e825e75afb97186f6ae1747f288
rocksdbPrebuiltSha.iosSimulatorArm64=6be1e55d5baec992b30389a4bc70510c30e3c7cabfc6b9cc47dfc86c799f01ab
rocksdbPrebuiltSha.linuxArm64=692c7776a814e3bae5237d952687a1a935bbcd2328a9e995c1fa7198dd4a6deb
rocksdbPrebuiltSha.linuxX64=19e1bd8b3509fd268b8d0d383fcae9b51c940aceaf4ba7516cea5e2fbe6b6a06
rocksdbPrebuiltSha.macosArm64=e687fd74d19848bca3632819c872db75bd42a0cf10d2f9e5bf606526257c0c09
rocksdbPrebuiltSha.macosX64=80cedb2c3d2d1cdd4f95a98f431ae068c03719ea93d812333b28d5e18e72e689
rocksdbPrebuiltSha.mingwX64=a232ff061e932c60c24b870fa191b9758f3ac39e9fd3ef12e97a24fce2905549
rocksdbPrebuiltSha.tvosArm64=895b59989e187a11ea14e41777f762f29fd64865360b843a26044a0aa2ed351e
rocksdbPrebuiltSha.tvosSimulatorArm64=af93b0b1c43c1259d88e5aa998c348ca4a285c0ff817118e2506b9c01d849850
rocksdbPrebuiltSha.watchosArm64=e41ce1e5c7377198c4010bc473d66a077590b4f229a0576068b5a0a41441d38a
rocksdbPrebuiltSha.watchosDeviceArm64=f2814d5690d2a0ad684ccbbe3d33d9a89e3744801e4cac1a43a0879560070c9c
rocksdbPrebuiltSha.watchosSimulatorArm64=053504918c082e0ae6a8d0be158ec9502f1ff6ba5c580057885cdc91cf4e6bdc
