kotlin.code.style=official

org.gradle.jvmargs=-Xms128m -Xmx1024m
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.stability.nowarn=true
kotlin.mpp.androidSourceSetLayoutVersion=2

rocksdbPrebuiltBaseUrl=https://github.com/marykdb/build-rocksdb/releases/download
rocksdbPrebuiltVersion=rocksdb-10.10.1-20260601T193510Z
rocksdbPrebuiltSha.androidNativeArm32=1fb82567d91980b628ad52e9bcaf0fc533974d765d6153fc4328c1198c93c9d5
rocksdbPrebuiltSha.androidNativeArm64=7d9ef6c08476523c3b91c379bc68c6e39da7d5539eda5720fc0ce3109b8198cb
rocksdbPrebuiltSha.androidNativeX64=41c2bb01e3a7bafe3b06184affa7c40ab6be8829ed6a66765cefc661eff97fd4
rocksdbPrebuiltSha.androidNativeX86=e10cc5d165b3d02c4f7d6802e6486a86d6d73b7ebfc4993478036174035ddbb4
rocksdbPrebuiltSha.iosArm64=3c56080628f5e7d11910441671482550c9551c0ee84e55485365ea40bd7c1e91
rocksdbPrebuiltSha.iosSimulatorArm64=e5f61820405e50a35bf0d796783228a27cd9640d90a9c830529a254a900af425
rocksdbPrebuiltSha.linuxArm64=552f54206f2d41d3aa4b26efa0ec96e74265b4fbb8254f40851afa9f3c9f55a0
rocksdbPrebuiltSha.linuxX64=8b4f0e8c5989bede653eb69efda5dccd83d3ddf0d901bdb2c033eab8503c164a
rocksdbPrebuiltSha.macosArm64=9debde2d89aa947b32f9b65dad9ed434da71be1dbdba16b3c55c54d77786f473
rocksdbPrebuiltSha.macosX64=ae63d5ff893d2260d8fb0461dc1910fafea4c55a17715d10bcf4f0dba7aba814
rocksdbPrebuiltSha.mingwX64=24c546a9f7ded3c81377b22404f904195234f4a5127ce4bd539768df87a25482
rocksdbPrebuiltSha.tvosArm64=f0bdb88be84fbd8c29165e9fc549060c1777dfab3a72008bb1305e1478e7a790
rocksdbPrebuiltSha.tvosSimulatorArm64=6792d7d92ec1aba87853d627f780383e1fab407aca53ddcc3fd1204bb0069b2c
rocksdbPrebuiltSha.watchosArm64=1b94dbb96b0341ed899999933c8e82dfd9d4cfcbbe1d6580ea6654b8aa5c899b
rocksdbPrebuiltSha.watchosDeviceArm64=a5c511f371050a5679a8c5452231458a2fef21639d3fe2a4801e88bdf7e4e83d
rocksdbPrebuiltSha.watchosSimulatorArm64=6f5164df396ca2c868ce9c4c271ef9a7258b2e89c6c0f5f2c0684cb5ff3d7251
