package maryk.rocksdb

const val RATE_LIMITER_DEFAULT_REFILL_PERIOD_MICROS = 100 * 1000L;
const val RATE_LIMITER_DEFAULT_FAIRNESS = 10;
val RATE_LIMITER_DEFAULT_MODE = RateLimiterMode.WRITES_ONLY;
const val RATE_LIMITER_DEFAULT_AUTOTUNE = false
