package maryk.rocksdb

const val SST_FILE_MANAGER_RATE_BYTES_PER_SEC_DEFAULT: Long = 0
const val SST_FILE_MANAGER_DELETE_EXISTING_TRASH_DEFAULT = true
const val SST_FILE_MANAGER_MAX_TRASH_DB_RATION_DEFAULT = 0.25
const val SST_FILE_MANAGER_BYTES_MAX_DELETE_CHUNK_DEFAULT = 64 * 1024 * 1024L
