#!/usr/bin/env python3
"""Project compatibility launcher for Kotlin Toolchain 0.12.2 (Python 3.9+)."""
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
from publishing_credentials import publishing_environment

ROOT = Path(__file__).resolve().parents[1]
NATIVE_TARGETS = (
    "androidNativeArm32", "androidNativeArm64", "androidNativeX64", "androidNativeX86",
    "iosArm64", "iosSimulatorArm64", "macosArm64", "macosX64", "linuxArm64", "linuxX64",
    "mingwX64", "tvosArm64", "tvosSimulatorArm64", "watchosArm64", "watchosDeviceArm64",
    "watchosSimulatorArm64",
)
SIMULATORS = {"iosSimulatorArm64": "iOS", "tvosSimulatorArm64": "tvOS", "watchosSimulatorArm64": "watchOS"}


def prepare(arguments):
    # 0.12.2 supplies friend paths during compilation, but omits them at native
    # test link time. Relative paths resolve against the compiler distribution,
    # so generate an absolute path for this checkout without committing it.
    lines = ["# Generated by scripts/kotlin_toolchain.py; do not edit."]
    for target in NATIVE_TARGETS:
        title = target[0].upper() + target[1:]
        klib = ROOT / "build" / "tasks" / f"_{ROOT.name}_compile{title}Debug" / f"{ROOT.name}.klib"
        flag = json.dumps(f"-friend-modules={klib}")
        lines += [f"test-settings@{target}:", "  kotlin:", f"    freeCompilerArgs: [{flag}]"]
    # Match the previous build: Maven Local needs no signing credentials.
    signed = "publish" in arguments and "mavenLocal" not in arguments
    central = "publish" in arguments and "mavenCentral" in arguments
    lines += ["settings:", "  publishing:", f"    signArtifacts: {str(signed).lower()}",
              "    mavenCentral:", f"      enabled: {str(central).lower()}"]
    destination = ROOT / ".toolchain" / "local.module-template.yaml"
    destination.parent.mkdir(exist_ok=True)
    content = "\n".join(lines) + "\n"
    if not destination.exists() or destination.read_text() != content:
        destination.write_text(content)


def run(*arguments, capture=False):
    result = subprocess.run(arguments, cwd=ROOT, text=True, check=True,
                            stdout=subprocess.PIPE if capture else None)
    return result.stdout if capture else None


def kotlin(*arguments):
    wrapper = ROOT / "scripts" / "toolchain" / ("kotlin.bat" if os.name == "nt" else "kotlin")
    environment = dict(os.environ, KOTLIN_CLI_WRAPPER_ALWAYS_USE_INTRINSIC_VERSION="1")
    environment = publishing_environment(ROOT, arguments, environment)
    subprocess.run([str(wrapper), *arguments], cwd=ROOT, env=environment, check=True)


def link_tests(target):
    task = f"link{target[0].upper() + target[1:]}TestDebug"
    kotlin("task", f":{ROOT.name}:{task}")
    return ROOT / "build" / "tasks" / f"_{ROOT.name}_{task}" / f"{ROOT.name}_test.kexe"


def simulator(target):
    # Toolchain 0.12.2 tries to execute tvOS/watchOS binaries on the host.
    # Use simctl for all simulator families and preserve already-booted devices.
    binary = link_tests(target)
    family = SIMULATORS[target]
    data = json.loads(run("xcrun", "simctl", "list", "devices", "available", "--json", capture=True))
    candidates = []
    for runtime, devices in data["devices"].items():
        if f"SimRuntime.{family}-" in runtime:
            version = tuple(int(value) for value in re.findall(r"\d+", runtime))
            candidates.extend((device, version) for device in devices if device.get("isAvailable", True))
    if not candidates:
        raise RuntimeError(f"No available {family} simulator. Install its runtime with Xcode first.")
    device, _ = max(candidates, key=lambda item: (item[0]["state"] == "Booted", item[1]))
    device_id = device["udid"]
    booted_here = device["state"] != "Booted"
    try:
        if booted_here:
            run("xcrun", "simctl", "boot", device_id)
        run("xcrun", "simctl", "bootstatus", device_id, "-b")
        run("xcrun", "simctl", "spawn", device_id, str(binary))
    finally:
        if booted_here:
            subprocess.run(["xcrun", "simctl", "shutdown", device_id], cwd=ROOT, check=False)


def check(targets):
    if not targets or any(target not in (*NATIVE_TARGETS, "jvm", "android") for target in targets):
        raise RuntimeError("Usage: ./kotlin check <target> [<target> ...]")
    database = ROOT / "build" / "test-database"
    for target in targets:
        print(f"Testing {target}", flush=True)
        shutil.rmtree(database, ignore_errors=True)
        database.mkdir(parents=True)
        try:
            if target in SIMULATORS:
                simulator(target)
            else:
                kotlin("test", "-p", target)
        finally:
            shutil.rmtree(database, ignore_errors=True)


def main(arguments):
    prepare(arguments)
    if arguments and arguments[0] == "check":
        check(arguments[1:])
    elif arguments and arguments[0] == "link-tests":
        if not arguments[1:] or any(target not in NATIVE_TARGETS for target in arguments[1:]):
            raise RuntimeError("Usage: ./kotlin link-tests <native-target> [<native-target> ...]")
        for target in arguments[1:]:
            link_tests(target)
    elif arguments and arguments[0] == "publish":
        # Build plugins are modules too, but are never part of this publication.
        if not any(arg in ("-m", "--module") or arg.startswith("--module=") for arg in arguments):
            arguments = ["publish", "-m", ROOT.name, *arguments[1:]]
        kotlin(*arguments)
    else:
        kotlin(*arguments)


if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except subprocess.CalledProcessError as error:
        sys.exit(error.returncode if error.returncode > 0 else 1)
    except (RuntimeError, OSError) as error:
        print(f"Error: {error}", file=sys.stderr)
        sys.exit(1)
